### ISSUE TITLE
[chapter 7] 定时器编程的问题

### ISSUE THREAD

**Issue by zzk0** [iosmanthus/Osmanthus-tutorial#1]
### 问题的产生
```
kinit_timer(200, timer_handler);
```
我将200（1s/200 = 5ms 输出一次tick）换成一个别的值，比如我想每秒钟计数一次，那么我把它换成1（1s/1 = 1s 输出一次tick）。是这样吗？

如果是的话，编译运行后却不是每秒输出一次。很奇怪。再换成10000也不是预期的那样。

### 问题：
这段代码里，frequency的意义是每秒中断产生的次数吗？如果是，那么设置成1的时候，为什么不是预期的那样？（是不是不同主机的问题呢？不知道在你那里是什么情况）
```
void kinit_timer(u32 frequency, KInterruptHandler handler) {
  kreg_int_handler(IRQ0, handler);

  u32 divisor = INPUT_FREQ / frequency;
  kout(0x43, 0x36, KBYTE);

  u8 l = divisor & 0xff;
  u8 h = (divisor >> 8) & 0xff;

  kout(0x40, l, KBYTE);
  kout(0x40, h, KBYTE);
}
```

**Comment by iosmanthus** [comment]
@zhouzekai 是的, `freq`表示每秒产生的时间中断的次数. 当时我也遇到这样的问题, 但是没有解决, 后来想着我只是要产生5ms一次的中断而已, 就没有管他了 :laughing:

**Comment by zzk0** [comment]
这个问题着实让人不知道从何处下手解决，难受😫

**Comment by iosmanthus** [comment]
@zhouzekai 其实这个时间中断我也只在上下文转换, 线程调度那块用到 :laughing:
